<?php

namespace USEC\StudentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends EntityRepository
{
	public function findAllSubscribed() {
		return $this->getEntityManager()
		->createQuery(
				'SELECT s FROM USECStudentBundle:Student s
				WHERE s.isRegistered = 1
				ORDER BY s.creationDate ASC'
		)
		->getResult();
	}
	
	public function findOneSubscribed($id) {
		return $this->getEntityManager()
		->createQuery(
				'SELECT s FROM USECStudentBundle:Student s
				WHERE s.isRegistered = 1
				AND s.id = :id'
		)
		->setMaxResults(1)
		->setParameter('id', $id)
		->getOneOrNullResult();
	}
}
