<?php

/*
 * This file is part of the Plateforme étudiante USEC.
*
* (c) USEC <contact@usec-utc.fr>
*
* For the full copyright and license information, please view the LICENSE
* file that was distributed with this source code.
*/

namespace USEC\StudentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StudyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudyRepository extends EntityRepository
{
	public function findAllAvailable() {
		return $this->getEntityManager()
			->createQuery(
					'SELECT s FROM USECStudentBundle:Study s
					WHERE s.closedDate IS NULL
					ORDER BY s.creationDate ASC'
			)
			->getResult();
	}
	
	public function findOneAvailableById($id) {
		return $this->getEntityManager()
		->createQuery(
				'SELECT s FROM USECStudentBundle:Study s
				WHERE s.closedDate IS NULL
				AND s.id = :id'
		)
		->setMaxResults(1)
		->setParameter('id', $id)
		->getOneOrNullResult();
	}
}
