parameters:
#    usec_student.example.class: USEC\StudentBundle\Example

services:
#    usec_student.example:
#        class: %usec_student.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
