USEC\StudentBundle\Entity\Student:
  properties:
    email:
      - NotBlank: ~
    phone:
      - NotBlank: ~
    name:
      - NotBlank: ~
    firstName:
      - NotBlank: ~
    username:
      - NotBlank: ~
    course:
      - NotBlank: ~
    endCourseSemester:
      - NotBlank: ~
    creationDate:
      - NotBlank: ~