USEC\StudentBundle\Entity\Student:
  properties:
    email:
      - NotBlank: ~
    phone:
      - NotBlank: ~
    name:
      - NotBlank: ~
    firstName:
      - NotBlank: ~
    username:
      - NotBlank: ~
    course:
      - NotBlank: ~
    endCourseSemester:
      - NotBlank: ~
    creationDate:
      - NotBlank: ~
      
USEC\StudentBundle\Entity\Study:
  properties:
    title:
      - NotBlank: ~
    description:
      - NotBlank: ~
    department:
      - NotBlank: ~
    estimatedPay:
      - NotBlank: ~
